pipeline:
  test:
    image: node
    commands:
      - npm install
      - npm run tests
  publish:
    image: plugins/docker
    tags: [ "${DRONE_BRANCH}_1.0.${DRONE_BUILD_NUMBER}" ]
    action: build
    secrets: [ docker_username, docker_password ]
    repo: jarlerik/node-kube-app
    when:
      event: [ push ]
      branch: master
  