pipeline:
  test:
    image: node
    commands:
      - npm install
      - npm run tests
  publish:
    image: plugins/docker
    repo: jarlerik/node-kude-app
    tags: [ "${DRONE_COMMIT_SHA:0:7}" ]
    secrets: [ docker_username, docker_password ]
    when:
      event: [ push ]
      branch: master
  