pipeline:
  test:
    image: node
    commands:
      - npm install
      - npm run tests
  publish:
    image: plugins/docker
    tags: [ "${DRONE_COMMIT_SHA:0:7}" ]
    action: build
    username: $DOCKER_USERNAME
    password: $DOCKER_PASSWORD
    repo: jarlerik/node-kude-app
    when:
      event: [ push ]
      branch: master
  