pipeline:
  test:
    image: node
    commands:
      - npm install
      - npm run tests
  publish:
    image: plugins/docker
    registry: hub.docker.com
    dockerfile: Dockerfile
    tags: ["commit_${DRONE_COMMIT}","build_${DRONE_BUILD_NUMBER}", "latest"]
    settings:
      repo: jarlerik/node-kude-app
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
    when:
      event: [ push ]
      branch: master
  