pipeline:
  test:
    image: node
    commands:
      - npm install
      - npm run tests
  publish:
    image: plugins/docker
    tags: [ "${DRONE_COMMIT_SHA:0:7}" ]
    action: build
    username: jarlerik
    password: 82$18G%!L$u@9SkS
    repo: jarlerik/node-kude-app
    when:
      event: [ push ]
      branch: master
  