pipeline:
  test:
    image: node
    commands:
      - npm install
      - npm run tests
  publish:
    image: plugins/docker
    tags: [ "${DRONE_COMMIT_SHA:0:7}" ]
    action: build
    commands:
      - echo "docker_username: ${DOCKER_USERNAME}"
      - echo "docker_password: ${DOCKER_PASSWORD}"
    repo: jarlerik/node-kude-app
    secrets: [docker_username, docker_password ]
    when:
      event: [ push ]
      branch: master
  